- hosts: 192.168.43.55
  tasks:

   - name: "installing jdk"
     shell: "rpm -ivh /root/jdk-8u171-linux-x64.rpm"
     ignore_errors: yes

   - name: "checking hadoop"
     shell: "hadoop version"
     register: hadoop_software
     ignore_errors: yes

   - name: "installing hadoop"
     shell: "rpm -ivh /root/hadoop-1.2.1-1.x86_64.rpm  --force"
     ignore_errors: yes
     register: hadoop_software
     when: hadoop_software.stdout == ""
  
 
   - name: "making namenode directory /nn"
     file: 
       path: "/nn"
       state: directory

   - name: "configuring hadoop hdfs-site.xml file"
     template: 
       src: "/etc/ansible/playbooks_menuprogram/hdfs_namenode.xml"
       dest: "/etc/hadoop/hdfs-site.xml"
  
   - name: "configuring hadoop core-site.xml file"
     template: 
       src: "/etc/ansible/playbooks_menuprogram/core.xml"
       dest: "/etc/hadoop/core-site.xml"

   - name: "formatting namenode node"
     shell: "echo Y | hadoop namenode -format"
     ignore_errors: yes

   - name: "Starting namenode services"
     shell: "hadoop-daemon.sh start namenode"

   - name: "Stoping firewalld"
     shell: "systemctl stop firewalld"
