- hosts: "{{ ip_add }}" 
  vars_files: 
   - variable.yml

  tasks:

    - name: "Installing httpd software"
      yum:
        name: httpd
        state: installed

    - name: "Copying web page to destination"
      copy: 
        dest: "/var/www/html"
        src: "/etc/ansible/playbooks/webpage.html"

    - name: "Starting web services"
      service: 
        name: httpd
        state: started

    - name: "Enabling Firewall"
      firewalld:
        port: 80/tcp
        state: enabled
        permanent: yes
        immediate: yes

    - name: "Creating new document root /var/www/doc_root "
      file:
        state: directory
        path: "{{ document_root }}"
    
    - name: "Copying configuration file to destination"
      template: 
        dest: "/etc/httpd/conf.d/web.conf"
        src: "/etc/ansible/playbooks/web.conf"
      notify:
        - "Restarting web services"

    - name: "Copying web page to destination"
      copy: 
        dest: "{{ document_root }}"
        src: "/etc/ansible/playbooks/webpage1.html"
    
    - name: "Enabling Firewall"
      firewalld:
        port: "{{ port_no }}/tcp"
        state: enabled
        permanent: yes
        immediate: yes
   
        
  handlers:  
    - name: "Restarting web services"
      service: 
        name: httpd
        state: restarted
